### ISSUE TITLE
 ACL Anthology RSS: Add a root-level RSS feed

### ISSUE THREAD

**Issue by CSchoel** [CSchoel/acl-anthology#2]
## Description

One of the main tasks for https://github.com/acl-org/acl-anthology/issues/358 is to build an RSS feed that one can subscribe to receive updates to the ACL anthology.

## Questions

From the main issue, it sounds like this RSS feed is also for structural updates to the ACL anthology and news posts, while my personal use case is to receive updates about newly published _papers_. Should there be multiple separate RSS feeds for that or should all of this information be put into a single RSS feed?

## DoD

- [x] Research existing Hugo plugins for RSS.
- [x] Decide on a strategy for implementation (existing plugin vs. custom solution).
- [x] Implement the RSS feed.
- [x] Make the RSS feed appear somewhere on the website.
- [ ] (Optional) Add the paper abstracts to the RSS feeds.
- [x] Test that the resulting feed is valid RSS.

**Comment by mbollmann** [comment]
You don't need a plugin, RSS feeds are core Hugo functionality. https://gohugo.io/templates/rss/

**Comment by akoehn** [comment]
And re combined vs. different feeds: I would go with two; they have nothing really in common.

**Comment by CSchoel** [comment]
Funny observation: The ACL anthology already _has_ an [RSS feed](https://aclanthology.org/index.xml), which is 42 MB in size. :laughing:

We probably want to deactivate this and limit our feeds to the entries of the last week. That most likely means the size of a single proceeding from a large conference, which is still a lot compared to the 10-15 updates that seem to be a common suggestion (see [StackOverflow question 1](https://stackoverflow.com/questions/23615944/how-many-entries-in-an-rss-feed-and-can-i-create-pages-for-rss-feed), [StackOverflow question 2](https://stackoverflow.com/questions/5318864/how-big-is-too-big-for-an-rss-feed-xml-file))

We could also think about having separate RSS feeds per event. However, that doesn't make the feeds that much smaller compared to restricting the top-level feed to items from the last week. The updates still come in bulks the size of a conference proceeding.

Update: Hugo also already adds RSS feeds for sections, so we have, for example, the following:
* https://aclanthology.org/papers/index.xml
* https://aclanthology.org/venues/index.xml
* https://aclanthology.org/events/index.xml
* https://aclanthology.org/posts/index.xml

This might actually be good enough for what we want to achieve in this issue. I'll have to take a closer look at them.

**Comment by mbollmann** [comment]
Huh, I don't think they were there from the beginning, maybe Hugo started turning them on by default at some point and we didn't notice when upgrading. :)

**Comment by CSchoel** [comment]
I was also surprised when I saw them. :laughing: 

After looking at them and playing around with the settings, I believe we can use these feeds, but the challenge is to keep the feed to a manageable size. This involves sorting them by date, and thus, first of all, parsing a date from the raw data. I wrote a pretty involved Python function for parsing a date from the `year` and `month` fields in the base XML files. It runs without errors for all existing papers, but I have to double-check the results. Maybe we also just want to use the `year` field instead, but then we have to see how large the RSS feed gets.

**Comment by mbollmann** [comment]
Modification times of the actual files might be more informative actually; if we add older proceedings, as we've done in the past with the MT Archive (https://github.com/acl-org/acl-anthology/issues/172), their `year` values will be in the past but we might still want them in the RSS as they've been newly added.

**Comment by mbollmann** [comment]
But then again, there might also be trivial changes to files (say, renaming an XML tag, or fixing a small error) that would cause these files to be modified... hmm...

**Comment by CSchoel** [comment]
@mbollmann If we want to go with the date when the files were added, there is an attribute called `ingest-date` in the `<volume>` tag in the XML files in the `data` folder. That seems like an ISO-formatted date that could work well for that purpose without being sensitive to trivial changes to the files themselves.

**Comment by mbollmann** [comment]
Oh, good catch! Yes, this should probably be used, if possible. While this attribute is technically optional, it might be that our current ingestion scripts always add it, so new volumes will always have it.

**Comment by CSchoel** [comment]
Using the `ingest-date` works well. I added a flag to the page generation script that allows using my regex-based function as a backup for unknown ingest dates.

Another question: With `rssLimit = 5000` we can cover one year worth of papers with less than 2 MB (which is still large for an RSS feed). Personally, I would love it to have the abstracts of the papers as a description in the feed, but that will blow up the size considerably. What do you think: Is it better to go with abstracts but restrict the size to a few 100 papers, or should we keep the time frame in the same order of magnitude and just report the titles?

**Comment by akoehn** [comment]
The problem I see here is that the rss for will probably be regenerated on every build of the anthology and, therefore, there will be no caching of the file.

No cache + large file = not good :-/

**Comment by CSchoel** [comment]
Good point. Considering that I will have much less time to continue this work after today, I'll go the easy route for now and just leave the abstracts out. I'll also set the `rssLimit` to `1000` so that we end up with 400kB instead of 2 MB. This means the RSS feed currently dates back to the 9th of July.
